### ISSUE TITLE
sort files in alphabetic order

### ISSUE THREAD

**Issue by ssolovey** [bmatcuk/Create-Playlist.workflow#1]
It is great script and would like to use it but it doesn't sort files alphabetically so instead of organized playlist I've got random list of files.
It would be great to have little enhancement :-)
Thank you so much in advance!

**Comment by bmatcuk** [comment]
Hmm, that's strange... on my machine, it sorts alphanumerically. I keep my music organized in folders by artist, and then album, with track names such as "01 Track 1.mp3". When I run this script on an artist folder, I end up with something like:
1. Artist/Album 1/01 Track 1.mp3
2. Artist/Album 1/02 Track 2.mp3
3. Artist/Album 1/...
4. Artist/Album 2/01 Track 1.mp3
5. Artist/Album 2/02 Track 2.mp3
6. Artist/Album 2/...

This doesn't happen for you?

**Comment by ssolovey** [comment]
I have the same structure in my folders and most of the files started as track number and then track name.
I have following output:
13-Van Morrison-Madame George.mp3
03-Van Morrison-Astral Weeks.mp3
11-Van Morrison-Ballerina.mp3
05-Van Morrison-Cyprus Avenue.mp3
09-Van Morrison-Slim Slow Slider.mp3
07-Van Morrison-The Way Young Lovers Do.mp3
10--Комментарии БГ.mp3
06--Комментарии БГ.mp3
04--Комментарии БГ.mp3
12--Заключение.mp3
08--Комментарии БГ.mp3
14--Заставка.mp3
01--Заставка.mp3
02--Вступление.mp3

**Comment by bmatcuk** [comment]
Hmm, I've made a small tweak to the script that I think might solve your problem. You can install the latest version by running the following in a Terminal window:

``` bash
cd ~/Library/Services/Create-Playlist.workflow
git pull
```

**Comment by ssolovey** [comment]
yeahh...
That works great!

I was trying to fix this error with "| sort" but I have no experience with bats script so it was no success.
Your solution is simple and works great!!!!

**Comment by ssolovey** [comment]
Thank you very very much :-))))

**Comment by bmatcuk** [comment]
Ya, `sort` was the next thing I would have tried if that didn't work =) Glad to help!
