### ISSUE TITLE
How to sort files by date created instead of alphabetical order ?

### ISSUE THREAD

**Issue by Pancho111** [bmatcuk/Create-Playlist.workflow#3]
Hello , how can I make it print sort by date created instead of alphabetical order please?
Thank you in advance .

**Comment by bmatcuk** [comment]
Hi @Pancho111 - the date at which the _file_ was created?

**Comment by Pancho111** [comment]
Hi Thank you for responding to my question ... what I please need is the mp3 files to play in the order they were created ,but the script is making the m3u with files in alphabetical order .
My music folder was created with the top hits first .
I would like to have the same order of the creation if possible.
I know some people need alphabetical order , if you please show me what to include in the script I can do it without interrupting the other fellows .
Thank you very much for your help , I really like your script.

**Comment by bmatcuk** [comment]
Sorry I haven't gotten back to you, @Pancho111... been busy. Do you still need this functionality?

**Comment by Pancho111** [comment]
Hi , yes I do please .. I closed it ,but I will reopen it if I can ..
thank you very much

**Comment by bmatcuk** [comment]
This was actually quite difficult, but I did manage to hack in some additional sorting options. When you run the workflow, it'll ask how you'd like to sort now including options for creation date and modified date, both ascending and descending.

Let me know if this works for you! =)

**Comment by Pancho111** [comment]
Oh my God  , what a great job !
Excellent , you are the best . nobody can beat this script now 
All complete , I don't think this needs anything else

thank you so much , i really appreciate it .

**Comment by bmatcuk** [comment]
You're welcome! Glad it works!
