### ISSUE TITLE
FLAC support

### ISSUE THREAD

**Issue by arturo71** [bmatcuk/Create-Playlist.workflow#4]
Hello. Can you add support for Flac files in Create-Playlist? This is an open source audio format.

Thanks,

Arturo

**Comment by bmatcuk** [comment]
Hey @arturo71 - that was easy enough =) Let me know if it works!

**Comment by arturo71** [comment]
It works like a charm! Thanks a lot

**Comment by bmatcuk** [comment]
You're welcome!
