### ISSUE TITLE
how about including flac?

### ISSUE THREAD

**Issue by crucco37** [bmatcuk/Create-Playlist.workflow#5]
that would be very nice indeed including more lossles formats these days. I'm using more and more flac music files. ogg could be interesting too.

kind regards
crucco

**Comment by bmatcuk** [comment]
Sure, that makes sense! What file extension do your flac files have? It should already include files with a `.flac` extension.

**Comment by crucco37** [comment]
Hey, thanks for responding so fast. The suffix is: '.flac‘.

You didn’t mention it on your help text so I assumed it isn’t included.

kind regards
crucco


-----Original Message-----
Von: Matcuk Bob <notifications@github.com>
Antworten: bmatcuk/Create-Playlist.workflow <reply@reply.github.com>
Datum: 22. Januar 2020 at 15:29:03
An: bmatcuk/Create-Playlist.workflow <create-playlist.workflow@noreply.github.com>
CC: crucco37 <crucco@riseup.net>, Author <author@noreply.github.com>
Betreff:  Re: [bmatcuk/Create-Playlist.workflow] how about including flac? (#5)

**Comment by bmatcuk** [comment]
Oh, my bad! I've updated the readme and added support for `.ogg` files, too =) Let me know if there are any other formats I should support!

**Comment by crucco37** [comment]
Hi,

maybe you should consider this: https://www.makeuseof.com/tag/audio-file-format-right-needs/

I’m not really sure what is common or what are all available file types that exist. 
The more, the better. If it’s only a routine that looks for file suffixes…

kind regards
crucco


-----Original Message-----
Von: Matcuk Bob <notifications@github.com>
Antworten: bmatcuk/Create-Playlist.workflow <reply@reply.github.com>
Datum: 22. Januar 2020 at 16:42:29
An: bmatcuk/Create-Playlist.workflow <create-playlist.workflow@noreply.github.com>
CC: crucco37 <crucco@riseup.net>, Author <author@noreply.github.com>
Betreff:  Re: [bmatcuk/Create-Playlist.workflow] how about including flac? (#5)

**Comment by bmatcuk** [comment]
Thanks for the suggestion... the article mentioned pcm, aiff, and alac in addition to the other formats that I already support. I've added them =)

**Comment by crucco37** [comment]
Hi,

finally I tried to use your script on my system. But I’m not able to use it because it seems
to be protected after cloning it. Maybe there’s also a translation problem because I’m running
my OS (still El Capitan) in german. There a 'Directory‹ is called ›Ordner‹.

Still no way to reproduce it in Automator because of the language differences.

kind regards
crucco


-----Original Message-----
Von: Matcuk Bob <notifications@github.com>
Antworten: bmatcuk/Create-Playlist.workflow <reply@reply.github.com>
Datum: 25. Januar 2020 at 15:26:58
An: bmatcuk/Create-Playlist.workflow <create-playlist.workflow@noreply.github.com>
CC: crucco37 <crucco@riseup.net>, Author <author@noreply.github.com>
Betreff:  Re: [bmatcuk/Create-Playlist.workflow] how about including flac? (#5)

**Comment by crucco37** [comment]
Well, I did it. Changing Directory to Ordner and getting the file rights.


-----Original Message-----
Von: Matcuk Bob <notifications@github.com>
Antworten: bmatcuk/Create-Playlist.workflow <reply@reply.github.com>
Datum: 25. Januar 2020 at 15:26:58
An: bmatcuk/Create-Playlist.workflow <create-playlist.workflow@noreply.github.com>
CC: crucco37 <crucco@riseup.net>, Author <author@noreply.github.com>
Betreff:  Re: [bmatcuk/Create-Playlist.workflow] how about including flac? (#5)

**Comment by crucco37** [comment]
But... I cannot use the ascending - descending dialogue. Descending order gives me only an empty file.
But I can live with it. So finally I’m really satisfied.

kind regards
crucco


-----Original Message-----
Von: Matcuk Bob <notifications@github.com>
Antworten: bmatcuk/Create-Playlist.workflow <reply@reply.github.com>
Datum: 25. Januar 2020 at 15:26:58
An: bmatcuk/Create-Playlist.workflow <create-playlist.workflow@noreply.github.com>
CC: crucco37 <crucco@riseup.net>, Author <author@noreply.github.com>
Betreff:  Re: [bmatcuk/Create-Playlist.workflow] how about including flac? (#5)

**Comment by bmatcuk** [comment]
Interesting... sorting by name descending was actually a bug; I just fixed that so it should work now. How did you have to change the file permissions to get it working? I'd like to document that for others.

**Comment by crucco37** [comment]
Hello, 

what I did was copying the file from your location
to my ~Library/Service folder with terminal
as you explained it.

Then I noticed when I opened it with Automator that it was 
locked and I couldn’t unlock it. Secondly I saw by looking 
for file rights and ownership that it was owned by root. 
That is not right for the ~Library/Service folder. 
So I changed ownership and exec permissions to the
local user. My local user has no admin rights.

I think you should not lock the file. But I’m not really 
sure about that.

It’s really hard to tell for me what’s best for others.

Do inform about file rights, ownership and locking/unlocking.
Perhaps being aware of that fact could help people.

Kind regards
crucco


-----Original Message-----
Von: Matcuk Bob <notifications@github.com>
Antworten: bmatcuk/Create-Playlist.workflow <reply@reply.github.com>
Datum: 26. Januar 2020 at 14:52:23
An: bmatcuk/Create-Playlist.workflow <create-playlist.workflow@noreply.github.com>
CC: crucco37 <crucco@riseup.net>, Author <author@noreply.github.com>
Betreff:  Re: [bmatcuk/Create-Playlist.workflow] how about including flac? (#5)

**Comment by bmatcuk** [comment]
Hmm, that's strange... I'll definitely add a note to the README.
