### ISSUE TITLE
the workflow does not appear in services

### ISSUE THREAD

**Issue by anatolenguyen** [bmatcuk/Create-Playlist.workflow#6]
hi bmatcuk, 

i was very excited to find this automator workflow for creating playlists—just what i needed to save me days of work!—but after installing, i was not able to find it in my services folder. i then tried to duplicate the automator commands from the photo you included, but was not able to get the m3u playlist to be created. i would very much appreciate any help that you could give me.

thanks in advance!

love,
a

UPDATE:

i reinstalled again and this time it appeared automatically in my services. so nevermind the above, and thanks so very much for creating this!

**Comment by bmatcuk** [comment]
Glad you got it working! =)

**Comment by anatolenguyen** [comment]
hi Bob,

again, thanks so much. what a big help for my workflow!

i have a request:

could you possibly help with a way to append—to the beginning of the m3u playlist name—the name of the parent folder (including "space + hyphen + space" as a separator)?

for example, if i have a folder named

Nirvana

with a subfolder called

Bleach

it would be super useful to name the—relative reference—created playlist

Nirvana - Bleach.m3u

i tried looking you up on Paypal but i didn’t find you.

please let me know if you use it and i will gladly
send a little thank you!

love,
a



________________________________
